ARMmbed/mbed-os-example-ble

BLE_EddystoneObserver/source/main.cpp

It is not authorized in C++ to use flexible arrays or arrays of zero length. 
While this is an extension enabled by ARMCC and GCC, this is not available from IAR.
This commit fix an invalid use of a flexible array in the EddystoneObserver example.

[EddystoneObserver] Fix usage of flexible arrays.

---

README.md

This is no longer necessary now that we have mbed OS 5 right? In the docs they're even grouped together... https://docs.mbed.com/docs/ble-intros/en/master/mbed_Classic/Overview/

Remove section on 'Porting your BLE app from mbed Classic to mbed OS'

---

README.md

The nucleo F411RE was referenced as a target supported oob in the README file. 
While the F411RE is supported it is not supported oob, the F401RE is. 
This patch fix the reference to the F411RE as a target supported OOB.

Fix reference to F401RE instead of F411RE

---

BLE_URIBeacon/source/main.cpp
BLE_URIBeacon/source/nrfConfigParamsPersistence.cpp

This set of patch improve the portability of BLE_URIBeacon example by removing references to the DFU and providing an in memory implementation of persistence functions.
It should fix #58

Fix#58: Inprove portability of BLE_URIBeacon

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_EddystoneObserver/mbed-os.lib
BLE_EddystoneService/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib
BLE_URIBeacon/mbed-os.lib

Please test/merge this PR and then tag Master with mbed-os-5.4.0-rc2

Updating mbed-os to mbed-os-5.4.0-rc2

---

BLE_BatteryLevel/source/main.cpp
BLE_Beacon/source/main.cpp
BLE_Button/source/main.cpp
BLE_EddystoneObserver/source/main.cpp
BLE_EddystoneService/source/main.cpp
BLE_GAPButton/source/main.cpp
BLE_HeartRate/source/main.cpp
BLE_LED/source/main.cpp
BLE_LEDBlinker/source/main.cpp
BLE_Thermometer/source/main.cpp

mbed OS defines a macro for EVENT QUEUE SIZE in EventQueue.h as 
#define EVENTS_QUEUE_SIZE (32*EVENTS_EVENT_SIZE) where EVENTS_EVENT_SIZE is:
#define EVENTS_EVENT_SIZE \
(EQUEUE_EVENT_SIZE - 2*sizeof(void*) + sizeof(mbed::Callback<void()>))
Using this pre-supplied macro is helpful rather than hard coding the event size as 16*32. For most cases this hard coding will be sufficient. But in order to make it safe for future & avoid potential queue under run, slightly modifying the code to use the pre-defined macro.
Tested on nRF52_DK platform.
Also resolves this issue: https://github.com/ARMmbed/mbed-os-example-ble/issues/49

Using predefined macro for EVENT SIZE.

---

BLE_EddystoneService/source/PersistentStorageHelper/ConfigParamsPersistence.cpp
BLE_EddystoneService/source/PersistentStorageHelper/nrfPersistentStorageHelper/nrfConfigParamsPersistence.cpp

pstorage is deprecated and no longer works in mbed OS 5.4 projects due to https://github.com/ARMmbed/mbed-os/issues/4181. This updates the driver to use fstorage, and also makes the driver work on nRF52.
@pan-

Change non-volatile storage driver for nRF51 to use fstorage

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_EddystoneObserver/mbed-os.lib
BLE_EddystoneService/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.5.1 .

Updating mbed-os to mbed-os-5.5.1

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_EddystoneObserver/mbed-os.lib
BLE_EddystoneService/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.5.2 .

Updating mbed-os to mbed-os-5.5.2

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_EddystoneObserver/mbed-os.lib
BLE_EddystoneService/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.5.3 .

Updating mbed-os to mbed-os-5.5.3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_EddystoneObserver/mbed-os.lib
BLE_EddystoneService/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.5.4 .

Updating mbed-os to mbed-os-5.5.4

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_EddystoneObserver/mbed-os.lib
BLE_EddystoneService/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.5.6 .

Updating mbed-os to mbed-os-5.5.6

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_EddystoneObserver/mbed-os.lib
BLE_EddystoneService/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.5.7 .

Updating mbed-os to mbed-os-5.5.7

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.6.0 .

Updating mbed-os to mbed-os-5.6.0

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.6.2 .

Updating mbed-os to mbed-os-5.6.2

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.6.3 .

Updating mbed-os to mbed-os-5.6.3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.6.4 .

Updating mbed-os to mbed-os-5.6.4

---

BLE_Beacon/readme.md

Seems the app went under a name change. Was a bit confusing at first, so it may help to change it in the docs.

Change name of nRF mobile app in example

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.6.6 .

Updating mbed-os to mbed-os-5.6.6

---

README.md

informations -> information
Change link https://github.com/ARMmbed/mbed-os/blob/master/docs/config_system.md to https://os.mbed.com/docs/latest/reference/configuration.html
Please check that the link to the documentation is the most appropriate one.
FYI @AnotherButler @MarceloSalazar

Fix a broken link replacing a github .md by a link into the docs

---

README.md

Fix a broken link to https://github.com/ARMmbed/mbed-os/tree/master/bluetooth/ble with a link to https://os.mbed.com/docs/latest/reference/ble.html and change the link text accordingly.
Please check that you are happy that the link into the docs is the most appropriate one.
FYI @AnotherButler @MarceloSalazar

Fix broken link to github module with link to web docs

---

README.md

The user has just cloned the latest version of the project, so suggesting "mbed update" is confusing as there is nothing to update. We are using the update to gather all the dependencies, and "mbed deploy" is a better command to do this.

Use "mbed deploy" instead of "mbed update"

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.7.6 .

Updating mbed-os to mbed-os-5.7.6

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.8.3 .

Updating mbed-os to mbed-os-5.8.3

---

BLE_SM/README.md
BLE_SM/mbed_app.json
BLE_SM/shields/TARGET_ST_BLUENRG.lib

This removes ST support for the Security Manager example as it's not supported by the ST host stack

Remove ST support from Security Manager example

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.8.6 .

Updating mbed-os to mbed-os-5.8.6

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.9.1 .

Updating mbed-os to mbed-os-5.9.1

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.9.3 .

Updating mbed-os to mbed-os-5.9.3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.9.6 .

Updating mbed-os to mbed-os-5.9.6

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.9.7 .

Updating mbed-os to mbed-os-5.9.7

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.10.2 .

Updating mbed-os to mbed-os-5.10.2

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.10.3 .

Updating mbed-os to mbed-os-5.10.3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.10.4 .

Updating mbed-os to mbed-os-5.10.4

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.11.4 .

Updating mbed-os to mbed-os-5.11.4

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.11.5 .

Updating mbed-os to mbed-os-5.11.5

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.12.0-rc2 .

Updating mbed-os to mbed-os-5.12.0-rc2

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.12.0-rc3 .

Updating mbed-os to mbed-os-5.12.0-rc3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.12.0-rc4 .

Updating mbed-os to mbed-os-5.12.0-rc4

---

BLE_GattServer/source/BLEProcess.h

Update example to use the new API. No functional change.

fix using mixed APIs in Gattserver example 

---

BLE_SM/README.md

The readme wasn't updated when the application was changed. This makes the readme describe the real application flow.

update readme to match application flow

---

BLE_Button/mbed_app.json
BLE_Button/source/main.cpp
BLE_GAPButton/mbed_app.json
BLE_GAPButton/source/main.cpp

NUCLEO_WB55RG requires a PullUp to work properly.
So a PullUp configuration option is added to mbed_app.json.

Define BLE BUTTON for NUCLEO_WB55RG

---

README.md

Basic mention of NUCLEO_WB55RG added now that target is supported in mbed-os master.

Update readme with some NUCLEO_WB55RG basic info

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.12.2 .

Updating mbed-os to mbed-os-5.12.2

---

BLE_Button/source/main.cpp

It seems that the example is broken and the "Button" device name is not advertised properly,
at least when testing with NUCLEO_WB55RG.
By comparing the example structure with HearRate, it seems that the advertising data in BLE_Button example is stored in a local variable of start_advertising data which may not be valid in memory after the function execution.
Aligning the implementation to HeartRate example seems to fix the problem.

BLE_Button: Fix advertising settings

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.12.3 .

Updating mbed-os to mbed-os-5.12.3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.12.4 .

Updating mbed-os to mbed-os-5.12.4

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.13.0-rc2 .

Updating mbed-os to mbed-os-5.13.0-rc2

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.13.0-rc3 .

Updating mbed-os to mbed-os-5.13.0-rc3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.13.0 .

Updating mbed-os to mbed-os-5.13.0

---

BLE_Thermometer/source/main.cpp
BLE_Thermometer/source/pretty_printer.h

This PR is to fix several deprecated API calls in BLE_Thermometer.
Note: This does **NOT** fix any deprecation warnings than come from _mbed-os_ itself. I'll create a separate/independent PR for that.
Also:
* Fix class name - it's obviously not BatteryDemo...
* Fix temperature variable type

Update thermometer test to use current APIs

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.13.3 .

Updating mbed-os to mbed-os-5.13.3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.14.0-rc1 .

Updating mbed-os to mbed-os-5.14.0-rc1

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

Once you get notification of the release being made public then tag Master with mbed-os-5.14.0-rc3 .

Updating mbed-os to mbed-os-5.14.0-rc3

---

BLE_Button/mbed-os.lib
BLE_Button/mbed_app.json
BLE_GAPButton/mbed-os.lib
BLE_GAPButton/mbed_app.json
README.md

This PR adds support for the Embedded Planet Agora (`EP_AGORA`) target to the BLE examples.

Add support for the Embedded Planet EP_AGORA target

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.15.0-rc1 .

Updating mbed-os to mbed-os-5.15.0-rc1

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.15.0-rc2 .

Updating mbed-os to mbed-os-5.15.0-rc2

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.15.0-rc3 .

Updating mbed-os to mbed-os-5.15.0-rc3

---

BLE_GattClient/source/main.cpp

This caused an error while adding the test for this example:
```
./source/main.cpp:489:22: error: comparison between pointer and integer
```

fixed a bug in BLE_GattClient

---

.circleci/config.yml
BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib

Add circle ci for building ble example

add circle ci

---

BLE_BatteryLevel/shields/TARGET_CORDIO_BLUENRG.lib
BLE_Beacon/shields/TARGET_CORDIO_BLUENRG.lib
BLE_Button/shields/TARGET_CORDIO_BLUENRG.lib
BLE_GAP/shields/TARGET_CORDIO_BLUENRG.lib
BLE_GAPButton/shields/TARGET_CORDIO_BLUENRG.lib
BLE_GattClient/shields/TARGET_CORDIO_BLUENRG.lib
BLE_GattServer/shields/TARGET_CORDIO_BLUENRG.lib
BLE_HeartRate/shields/TARGET_CORDIO_BLUENRG.lib
BLE_LED/shields/TARGET_CORDIO_BLUENRG.lib
BLE_LEDBlinker/shields/TARGET_CORDIO_BLUENRG.lib
BLE_PeriodicAdvertising/shields/TARGET_CORDIO_BLUENRG.lib
BLE_Privacy/shields/TARGET_CORDIO_BLUENRG.lib
BLE_SM/shields/TARGET_CORDIO_BLUENRG.lib
BLE_Thermometer/shields/TARGET_CORDIO_BLUENRG.lib

Upstream TARGET_CORDIO_BLUENRG.lib to latest master SHA to fix the https://github.com/ARMmbed/mbed-os/pull/12609 PR CI failure due to the usage of deprecated API.
@donatieng, @pan-

Upstream ble example cordio bluenrg

---

BLE_GAP/source/main.cpp

`wait` and `wait_ms` are removed from Mbed OS source in the [PR#12572](https://github.com/ARMmbed/mbed-os/pull/12572), so modified source to use thread_sleep_for API.
@evedon, @donatieng @pan-

Remove wait deprecated API usage

---

BLE_BatteryLevel/source/pretty_printer.h
BLE_Beacon/source/pretty_printer.h
BLE_Button/source/pretty_printer.h
BLE_GAP/source/main.cpp
BLE_GAP/source/pretty_printer.h
BLE_GAPButton/source/pretty_printer.h
BLE_GattClient/source/main.cpp
BLE_GattClient/source/pretty_printer.h
BLE_GattServer/source/pretty_printer.h
BLE_HeartRate/source/pretty_printer.h
BLE_LED/source/pretty_printer.h
BLE_LEDBlinker/source/main.cpp
BLE_LEDBlinker/source/pretty_printer.h
BLE_PeriodicAdvertising/source/pretty_printer.h
BLE_Privacy/source/main.cpp
BLE_Privacy/source/pretty_printer.h
BLE_SM/source/main.cpp
BLE_SM/source/pretty_printer.h
BLE_Thermometer/source/pretty_printer.h

This PR replaces usages of deprecated types in `Gap::` that are not warned by the compiler but will not be available anymore once https://github.com/ARMmbed/mbed-os/pull/12730 is merged. (Note: This does **not** depend on that PR.)
Types replaced:
* `Gap::Phy_t` -> `ble::phy_t`
* `Gap::Handle_t` -> `ble::connection_handle_t`
* `GapAdvertisingData::LE_GENERAL_DISCOVERABLE` -> `ble::adv_data_flags_t(value).getGeneralDiscoverable()`
* `Gap::CentralPrivacyConfiguration_t` -> `ble::central_privacy_configuration_t`
The legacy types exist in the legacy Gap class only which will be removed from mbed-os. The current Gap APIs only use the new types.

Fix deprecated Gap type usages

---

BLE_BatteryLevel/source/pretty_printer.h
BLE_Beacon/source/pretty_printer.h
BLE_Button/source/pretty_printer.h
BLE_GAP/source/main.cpp
BLE_GAP/source/pretty_printer.h
BLE_GAPButton/source/pretty_printer.h
BLE_GattClient/source/main.cpp
BLE_GattClient/source/pretty_printer.h
BLE_GattServer/source/pretty_printer.h
BLE_HeartRate/source/pretty_printer.h
BLE_LED/source/pretty_printer.h
BLE_LEDBlinker/source/main.cpp
BLE_LEDBlinker/source/pretty_printer.h
BLE_PeriodicAdvertising/source/pretty_printer.h
BLE_Privacy/source/main.cpp
BLE_Privacy/source/pretty_printer.h
BLE_SM/source/main.cpp
BLE_SM/source/pretty_printer.h
BLE_Thermometer/source/pretty_printer.h

Reverts ARMmbed/mbed-os-example-ble#289

Revert "Fix deprecated Gap type usages"

---

BLE_BatteryLevel/source/pretty_printer.h
BLE_Beacon/source/pretty_printer.h
BLE_Button/source/pretty_printer.h
BLE_GAP/source/main.cpp
BLE_GAP/source/pretty_printer.h
BLE_GAPButton/source/pretty_printer.h
BLE_GattClient/source/main.cpp
BLE_GattClient/source/pretty_printer.h
BLE_GattServer/source/pretty_printer.h
BLE_HeartRate/source/pretty_printer.h
BLE_LED/source/pretty_printer.h
BLE_LEDBlinker/source/main.cpp
BLE_LEDBlinker/source/pretty_printer.h
BLE_PeriodicAdvertising/source/pretty_printer.h
BLE_Privacy/source/main.cpp
BLE_Privacy/source/pretty_printer.h
BLE_SM/source/main.cpp
BLE_SM/source/pretty_printer.h
BLE_Thermometer/source/pretty_printer.h

In https://github.com/ARMmbed/mbed-os/pull/12730 we have removed legacy address-related types (BLEProtocol:: namespace) in favour of new once in ble:: namespace. This PR updates examples
so they will continue to work the latest Mbed OS.
Changes:
* `BLEProtocol::AddressType_t` -> `ble::own_address_type_t`
* `BLEProtocol::AddressBytes_t` -> `ble::address_t`
Additionally, in #289 we fixed types for Gap, but it got reverted because it contains a typo fix which hasn't landed in mbed-os repo yet. This PR also brings that back.
* `Gap::Phy_t` -> `ble::phy_t`
* `Gap::Handle_t` -> `ble::connection_handle_t`
* `GapAdvertisingData::LE_GENERAL_DISCOVERABLE` -> `ble::adv_data_flags_t(value).getGeneralDiscoverable()`
* `Gap::CentralPrivacyConfiguration_t` -> `ble::central_privacy_configuration_t` …

Use new types for BLE address and Gap

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.15.3 .

Updating mbed-os to mbed-os-5.15.3

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

release branch with mbed-os-5.15.4 .

Updating mbed-os to mbed-os-5.15.4

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

mbed-os-6.1.0 release of mbed-os.

Update for mbed-os-6.1.0

---

.circleci/config.yml

CI testing got some bugs:
1. Reuse of BUILD folder to speed up building process cause some image not been build properly. So disable the reuse of BUILD folder. 
2. Break command in bash not throw any error code, some build failure would be missed, change to `exit 1` to deliberate to throw errors if build failed

Fix CI bugs

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

mbed-os-6.2.0 release of mbed-os.

Update for mbed-os-6.2.0

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

mbed-os-5.15.5 release of mbed-os.

Update for mbed-os-5.15.5

---

BLE_BatteryLevel/mbed-os.lib
BLE_Beacon/mbed-os.lib
BLE_Button/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GAPButton/mbed-os.lib
BLE_GattClient/mbed-os.lib
BLE_GattServer/mbed-os.lib
BLE_HeartRate/mbed-os.lib
BLE_LED/mbed-os.lib
BLE_LEDBlinker/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_Privacy/mbed-os.lib
BLE_SM/mbed-os.lib
BLE_Thermometer/mbed-os.lib
deprecated/BLE_BatteryLevel/mbed-os.lib
deprecated/BLE_Beacon/mbed-os.lib
deprecated/BLE_Button/mbed-os.lib
deprecated/BLE_GAP/mbed-os.lib
deprecated/BLE_GAPButton/mbed-os.lib
deprecated/BLE_GattClient/mbed-os.lib
deprecated/BLE_GattServer/mbed-os.lib
deprecated/BLE_HeartRate/mbed-os.lib
deprecated/BLE_LED/mbed-os.lib
deprecated/BLE_LEDBlinker/mbed-os.lib
deprecated/BLE_Privacy/mbed-os.lib
deprecated/BLE_SM/mbed-os.lib
deprecated/BLE_Thermometer/mbed-os.lib

mbed-os-6.2.1 release of mbed-os.

Update for mbed-os-6.2.1

---

BLE_GAP/source/main.cpp

Cherry pick commit 31426f1 from master branch to fix same issue in mbed-os-5-15 branch
Fixes https://github.com/ARMmbed/mbed-os-example-ble/issues/312
----------------------------------------------------------------------------------------------------------------
[x] Patch update (Bug fix)
----------------------------------------------------------------------------------------------------------------
@LDong-Arm - since this commit was your work originally, would you be so kind as to review my PR?

BLE_GAP: do not use CONNECTABLE_UNDIRECTED with extended advertising

---

BLE_GAP/source/main.cpp

Fixes headers so that ble refactor can get through CI. These internal headers should never be included directly.

BLE: remove internal includes

---

BLE_Button/CMakeLists.txt

Mbed OS has multiple targets that can be linked to as required.
Reviewers: @0xc0170 @rajkan01

CMake: Add required Mbed OS component

---

BLE_LED/CMakeLists.txt

They are now prefixed with "mbed-" instead of "mbed-os-"
Reviewers
@0xc0170 
@rajkan01

CMake: Use renamed Mbed CMake targets component

---

BLE_LED/CMakeLists.txt

- Called mbed_set_post_build API for setting post-build operations
- Update CMake minimum version required from 3.18.2 to 3.19.0
- Replace mbed-os source path MBED_ROOT with MBED_PATH in CMakeLists.txt

CMake: Call mbed_set_post_build API for setting post build operations

---

BLE_Advertising/CMakeLists.txt
BLE_Advertising/mbed-os-ble-utils.lib

- Added the missing `mbed-os-ble-utils` directory in CMakeLists.txt which is normally created after `mbed deploy` command
@0xc0170 @pan-

CMake: Include the third party library

---

BLE_Advertising/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GattClient_CharacteristicUpdates/mbed-os.lib
BLE_GattClient_CharacteristicWrite/mbed-os.lib
BLE_GattServer_AddService/mbed-os.lib
BLE_GattServer_CharacteristicUpdates/mbed-os.lib
BLE_GattServer_CharacteristicWrite/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_SecurityAndPrivacy/mbed-os.lib

Update the Mbed OS version pointed at by this example's development branch to the Mbed OS development branch. This ensures that the development branch will build using the latest mbed-os after a checkout and deploy.

Update mbed-os to its development branch

---

BLE_GAP/source/main.cpp

Fix example when ext advertising is disabled.

Fix extended advertising guards

---

BLE_Advertising/CMakeLists.txt
BLE_GAP/CMakeLists.txt
BLE_GattClient_CharacteristicUpdates/CMakeLists.txt
BLE_GattClient_CharacteristicWrite/CMakeLists.txt
BLE_GattServer_AddService/CMakeLists.txt
BLE_GattServer_CharacteristicUpdates/CMakeLists.txt
BLE_GattServer_CharacteristicWrite/CMakeLists.txt
BLE_GattServer_ExperimentalServices/CMakeLists.txt
BLE_PeriodicAdvertising/CMakeLists.txt
BLE_SecurityAndPrivacy/CMakeLists.txt

`mbed_set_mbed_target_linker_script` was removed from mbed-os.
This PR depends on ARMmbed/mbed-os#14199

Remove deprecated function from CMakeLists.txt

---

BLE_Advertising/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GattClient_CharacteristicUpdates/mbed-os.lib
BLE_GattClient_CharacteristicWrite/mbed-os.lib
BLE_GattServer_AddService/mbed-os.lib
BLE_GattServer_CharacteristicUpdates/mbed-os.lib
BLE_GattServer_CharacteristicWrite/mbed-os.lib
BLE_GattServer_ExperimentalServices/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_SecurityAndPrivacy/mbed-os.lib

mbed-os-6.9.0 release of mbed-os.

Update for mbed-os-6.9.0

---

BLE_Advertising/CMakeLists.txt
BLE_GAP/CMakeLists.txt
BLE_GattClient_CharacteristicUpdates/CMakeLists.txt
BLE_GattClient_CharacteristicWrite/CMakeLists.txt
BLE_GattServer_AddService/CMakeLists.txt
BLE_GattServer_CharacteristicUpdates/CMakeLists.txt
BLE_GattServer_CharacteristicWrite/CMakeLists.txt
BLE_GattServer_ExperimentalServices/CMakeLists.txt
BLE_PeriodicAdvertising/CMakeLists.txt
BLE_SecurityAndPrivacy/CMakeLists.txt
BLE_SupportedFeatures/CMakeLists.txt
README.md

The deprecated function call `mbed_configure_app_target()` is removed from each example's `CMakeLists.txt`.
The top-level `README.md` is updated to add instructions for using Mbed CLI 2 with the examples, as well as align the structure of the file with other examples. Some incorrect information is also removed.

Update examples for Mbed CLI 2

---

BLE_Advertising/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GattClient_CharacteristicUpdates/mbed-os.lib
BLE_GattClient_CharacteristicWrite/mbed-os.lib
BLE_GattServer_AddService/mbed-os.lib
BLE_GattServer_CharacteristicUpdates/mbed-os.lib
BLE_GattServer_CharacteristicWrite/mbed-os.lib
BLE_GattServer_ExperimentalServices/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_SecurityAndPrivacy/mbed-os.lib
BLE_SupportedFeatures/mbed-os.lib

mbed-os-6.11.0 release of mbed-os.

Update for mbed-os-6.11.0

---

BLE_GAP/source/main.cpp

Set destroyed too early. We need to wait until it stops. The change is that I moved the block that destroys the set and continues the demo to the advertising end event (only for extended advertising).

Don't destroy set before it stops

---

BLE_Advertising/CMakeLists.txt
BLE_GAP/CMakeLists.txt
BLE_GattClient_CharacteristicUpdates/CMakeLists.txt
BLE_GattClient_CharacteristicWrite/CMakeLists.txt
BLE_GattServer_AddService/CMakeLists.txt
BLE_GattServer_CharacteristicUpdates/CMakeLists.txt
BLE_GattServer_CharacteristicWrite/CMakeLists.txt
BLE_GattServer_ExperimentalServices/CMakeLists.txt
BLE_PeriodicAdvertising/CMakeLists.txt
BLE_SecurityAndPrivacy/CMakeLists.txt
BLE_SupportedFeatures/CMakeLists.txt

So CMake can work correctly we need to define our project before we add
dependencies, otherwise the project we depend on will be registered as
the current project.

CMake: Make applications the top level CMake projects

---

BLE_Advertising/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GattClient_CharacteristicUpdates/mbed-os.lib
BLE_GattClient_CharacteristicWrite/mbed-os.lib
BLE_GattServer_AddService/mbed-os.lib
BLE_GattServer_CharacteristicUpdates/mbed-os.lib
BLE_GattServer_CharacteristicWrite/mbed-os.lib
BLE_GattServer_ExperimentalServices/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_SecurityAndPrivacy/mbed-os.lib
BLE_SupportedFeatures/mbed-os.lib

mbed-os-6.15.0 release of mbed-os.

Update for mbed-os-6.15.0

---

BLE_Advertising/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GattClient_CharacteristicUpdates/mbed-os.lib
BLE_GattClient_CharacteristicWrite/mbed-os.lib
BLE_GattServer_AddService/mbed-os.lib
BLE_GattServer_CharacteristicUpdates/mbed-os.lib
BLE_GattServer_CharacteristicWrite/mbed-os.lib
BLE_GattServer_ExperimentalServices/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_SecurityAndPrivacy/mbed-os.lib
BLE_SupportedFeatures/mbed-os.lib

mbed-os-6.15.1 release of mbed-os.

Update for mbed-os-6.15.1

---

BLE_Advertising/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GattClient_CharacteristicUpdates/mbed-os.lib
BLE_GattClient_CharacteristicWrite/mbed-os.lib
BLE_GattServer_AddService/mbed-os.lib
BLE_GattServer_CharacteristicUpdates/mbed-os.lib
BLE_GattServer_CharacteristicWrite/mbed-os.lib
BLE_GattServer_ExperimentalServices/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_SecurityAndPrivacy/mbed-os.lib
BLE_SupportedFeatures/mbed-os.lib

mbed-os-6.16.0 release of mbed-os.

Update for mbed-os-6.16.0

---

BLE_Advertising/mbed-os.lib
BLE_GAP/mbed-os.lib
BLE_GattClient_CharacteristicUpdates/mbed-os.lib
BLE_GattClient_CharacteristicWrite/mbed-os.lib
BLE_GattServer_AddService/mbed-os.lib
BLE_GattServer_CharacteristicUpdates/mbed-os.lib
BLE_GattServer_CharacteristicWrite/mbed-os.lib
BLE_GattServer_ExperimentalServices/mbed-os.lib
BLE_PeriodicAdvertising/mbed-os.lib
BLE_SecurityAndPrivacy/mbed-os.lib
BLE_SupportedFeatures/mbed-os.lib

mbed-os-6.17.0 release of mbed-os.

Update for mbed-os-6.17.0
