- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
- BLE_URIBeacon/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.3.3
> Updating mbed-os to mbed-os-5.3.3

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
- BLE_URIBeacon/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.3.4
> Updating mbed-os to mbed-os-5.3.4

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
- BLE_URIBeacon/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.3.5
> Updating mbed-os to mbed-os-5.3.5

- BLE_BatteryLevel/shields/TARGET_ST_BLUENRG.lib
- BLE_Beacon/shields/TARGET_ST_BLUENRG.lib
- BLE_Button/shields/TARGET_ST_BLUENRG.lib
- BLE_EddystoneObserver/shields/TARGET_ST_BLUENRG.lib
- BLE_EddystoneService/shields/TARGET_ST_BLUENRG.lib
- BLE_GAPButton/shields/TARGET_ST_BLUENRG.lib
- BLE_HeartRate/shields/TARGET_ST_BLUENRG.lib
- BLE_LED/shields/TARGET_ST_BLUENRG.lib
- BLE_LEDBlinker/shields/TARGET_ST_BLUENRG.lib
- BLE_Thermometer/shields/TARGET_ST_BLUENRG.lib
- BLE_URIBeacon/shields/TARGET_ST_BLUENRG.lib
> Update reference to the ST shield library

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
- BLE_URIBeacon/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.3.6
> Updating mbed-os to mbed-os-5.3.6

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.4.1
> Updating mbed-os to mbed-os-5.4.1

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.4.2
> Updating mbed-os to mbed-os-5.4.2

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.4.4
> Updating mbed-os to mbed-os-5.4.4

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.4.5
> Updating mbed-os to mbed-os-5.4.5

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.4.6
> Updating mbed-os to mbed-os-5.4.6

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.4.7
> Updating mbed-os to mbed-os-5.4.7

- BLE_BatteryLevel/mbed_app.json
- BLE_BatteryLevel/shields/TARGET_ST_BLUENRG.lib
- BLE_Beacon/mbed_app.json
- BLE_Beacon/shields/TARGET_ST_BLUENRG.lib
- BLE_Button/mbed_app.json
- BLE_Button/shields/TARGET_ST_BLUENRG.lib
- BLE_EddystoneObserver/mbed_app.json
- BLE_EddystoneObserver/shields/TARGET_ST_BLUENRG.lib
- BLE_EddystoneService/mbed_app.json
- BLE_EddystoneService/shields/TARGET_ST_BLUENRG.lib
- BLE_GAPButton/mbed_app.json
- BLE_GAPButton/shields/TARGET_ST_BLUENRG.lib
- BLE_HeartRate/mbed_app.json
- BLE_HeartRate/shields/TARGET_ST_BLUENRG.lib
- BLE_LED/mbed_app.json
- BLE_LED/shields/TARGET_ST_BLUENRG.lib
- BLE_LEDBlinker/mbed_app.json
- BLE_LEDBlinker/shields/TARGET_ST_BLUENRG.lib
- BLE_Thermometer/mbed_app.json
- BLE_Thermometer/shields/TARGET_ST_BLUENRG.lib
- README.md
@pan- please review/merge this PR
> Update reference to ST BLUENRG lib

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_EddystoneObserver/mbed-os.lib
- BLE_EddystoneService/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Please test/merge this PR and then tag Master with mbed-os-5.5.0
> Updating mbed-os to mbed-os-5.5.0

- BLE_BatteryLevel/mbed_app.json
- BLE_Beacon/mbed_app.json
- BLE_Button/mbed_app.json
- BLE_EddystoneObserver/mbed_app.json
- BLE_EddystoneService/mbed_app.json
- BLE_GAPButton/mbed_app.json
- BLE_HeartRate/mbed_app.json
- BLE_LED/mbed_app.json
- BLE_LEDBlinker/mbed_app.json
- BLE_Thermometer/mbed_app.json
- README.md
> DISCO_L475VG_IOT01A: Add this platform in the supported list of boards

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.7.2 .
> Updating mbed-os to mbed-os-5.7.2

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.7.3 .
> Updating mbed-os to mbed-os-5.7.3

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.7.4 .
> Updating mbed-os to mbed-os-5.7.4

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.7.5 .
> Updating mbed-os to mbed-os-5.7.5

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.8.1 .
> Updating mbed-os to mbed-os-5.8.1

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.8.2 .
> Updating mbed-os to mbed-os-5.8.2

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.8.4 .
> Updating mbed-os to mbed-os-5.8.4

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.8.5 .
> Updating mbed-os to mbed-os-5.8.5

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAP/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_GattServer/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Privacy/mbed-os.lib
- BLE_SM/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.9.2 .
> Updating mbed-os to mbed-os-5.9.2

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAP/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_GattClient/mbed-os.lib
- BLE_GattServer/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Privacy/mbed-os.lib
- BLE_SM/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.9.4 .
> Updating mbed-os to mbed-os-5.9.4

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAP/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_GattClient/mbed-os.lib
- BLE_GattServer/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_Privacy/mbed-os.lib
- BLE_SM/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
Once you get notification of the release being made public then tag Master with mbed-os-5.9.5 .
> Updating mbed-os to mbed-os-5.9.5

- BLE_HeartRate/readme.md
> Remove reference to Panobike

- BLE_Thermometer/readme.md
> Fix link to health thermometer GATT service

- Jenkinsfile
Calls library in the test repo to run the multibranch or Pull-request job
This hook shall only run for trusted authors
> Add a trigger for the new library in tests repo

- BLE_GAP/source/main.cpp
- BLE_GattClient/source/main.cpp
This was done last week was just waiting for .lib upgrade
> Add data length change to gap and ATT_MTU change to gatt client

- BLE_GAP/source/main.cpp
IAR doesn't like the use of size for a template
> Fix name of template for IAR

- BLE_GattClient/source/main.cpp
Use NULL instead of false in GattClient example.
> Fix pointer check

- tests/README.md
- tests/broadcast.log
This test is able to test the ble example up to the stage of print out itself MAC address
> add compare log test

- BLE_BatteryLevel/source/main.cpp
- BLE_BatteryLevel/source/pretty_printer.h
- BLE_Beacon/source/pretty_printer.h
- BLE_Button/mbed_app.json
- BLE_Button/source/pretty_printer.h
- BLE_GAP/source/main.cpp
- BLE_GAP/source/pretty_printer.h
- BLE_GAPButton/mbed_app.json
- BLE_GAPButton/source/main.cpp
- BLE_GAPButton/source/pretty_printer.h
- BLE_GattClient/source/BLEProcess.h
- BLE_GattClient/source/main.cpp
- BLE_GattClient/source/pretty_printer.h
- BLE_GattServer/source/BLEProcess.h
- BLE_GattServer/source/main.cpp
- BLE_GattServer/source/pretty_printer.h
- BLE_HeartRate/source/pretty_printer.h
- BLE_LED/source/pretty_printer.h
- BLE_LEDBlinker/source/pretty_printer.h
- BLE_PeriodicAdvertising/source/main.cpp
- BLE_PeriodicAdvertising/source/pretty_printer.h
- BLE_Privacy/source/main.cpp
- BLE_Privacy/source/pretty_printer.h
- BLE_SM/README.md
- BLE_SM/source/main.cpp
- BLE_SM/source/pretty_printer.h
- BLE_Thermometer/source/pretty_printer.h
Also update the third party library to point to a version that does
not use deprecated BLE APIs.
Reviewers
@paul-szczepanek-arm  @pan-
> Replace deprecated BLE APIs

- .circleci/config.yml
enable CI build 2 targets in parallel.
So CI build will be speed up
> enable CI build 2 targets in parallel

- BLE_BatteryLevel/mbed-os.lib
- BLE_Beacon/mbed-os.lib
- BLE_Button/mbed-os.lib
- BLE_GAP/mbed-os.lib
- BLE_GAPButton/mbed-os.lib
- BLE_GattClient/mbed-os.lib
- BLE_GattServer/mbed-os.lib
- BLE_HeartRate/mbed-os.lib
- BLE_LED/mbed-os.lib
- BLE_LEDBlinker/mbed-os.lib
- BLE_PeriodicAdvertising/mbed-os.lib
- BLE_Privacy/mbed-os.lib
- BLE_SM/mbed-os.lib
- BLE_Thermometer/mbed-os.lib
- deprecated/BLE_BatteryLevel/mbed-os.lib
- deprecated/BLE_Beacon/mbed-os.lib
- deprecated/BLE_Button/mbed-os.lib
- deprecated/BLE_GAP/mbed-os.lib
- deprecated/BLE_GAPButton/mbed-os.lib
- deprecated/BLE_GattClient/mbed-os.lib
- deprecated/BLE_GattServer/mbed-os.lib
- deprecated/BLE_HeartRate/mbed-os.lib
- deprecated/BLE_LED/mbed-os.lib
- deprecated/BLE_LEDBlinker/mbed-os.lib
- deprecated/BLE_Privacy/mbed-os.lib
- deprecated/BLE_SM/mbed-os.lib
- deprecated/BLE_Thermometer/mbed-os.lib
release branch with mbed-os-5.15.2 .
> Updating mbed-os to mbed-os-5.15.2

- BLE_BatteryLevel/mbed_app.json
- BLE_BatteryLevel/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_Beacon/mbed_app.json
- BLE_Beacon/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_Button/mbed_app.json
- BLE_Button/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_GAP/mbed_app.json
- BLE_GAP/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_GAPButton/mbed_app.json
- BLE_GAPButton/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_GattClient/mbed_app.json
- BLE_GattClient/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_GattServer/mbed_app.json
- BLE_GattServer/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_HeartRate/mbed_app.json
- BLE_HeartRate/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_LED/mbed_app.json
- BLE_LED/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_LEDBlinker/mbed_app.json
- BLE_LEDBlinker/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_PeriodicAdvertising/mbed_app.json
- BLE_PeriodicAdvertising/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_Privacy/mbed_app.json
- BLE_Privacy/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_SM/mbed_app.json
- BLE_SM/shields/TARGET_CORDIO_BLUENRG.lib
- BLE_Thermometer/mbed_app.json
- BLE_Thermometer/shields/TARGET_CORDIO_BLUENRG.lib
- README.md
Hi
BlueNRG chip is now a mbed-os BLE component.
PR needed for:
https://github.com/ARMmbed/mbed-os/pull/12456
> COMPONENT_BlueNRG_MS creation in mbed-os

- tests/ble_gattclient.log
- tests/ble_gattserver.log
- tests/ble_periodicadvertising_NotSupport.log
- tests/ble_privacy.log
- tests/ble_sm.log
> add more log compare test

- BLE_GattServer/README.md
- README.md
This PR
* adds a README to the BLE_GattServer example
* removes outdated information in the top-level README
> OoB docs update

- BLE_Privacy/README.md
Not all privacy features are exercised in the example. Put a disclaimer explaining that more privacy features will be added to the example as new features are added to mbed-os.
> Add a disclaimer to privacy example

- BLE_Button/shields/CMakeLists.txt
> Remove shields directory as done in the upstream repository

- BLE_SupportedFeatures/CMakeLists.txt
- BLE_SupportedFeatures/mbed-os.lib
- BLE_SupportedFeatures/mbed_app.json
- BLE_SupportedFeatures/readme.md
- BLE_SupportedFeatures/source/main.cpp
Add examples that shows supported feature on the board.
> Add supported features example

- BLE_Advertising/source/main.cpp
The advertising example was sending the wrong payload because during battery level update the data builder being reused was the one used for scan response payload instead of the normal payload. This fixes it by reversing the order of setting the payloads. Added more comments to explain this.
> fix payload in advertising example

- README.md
@pan- @MarceloSalazar @avilei please review this updated version of README.md
> Refresh and add reference to X-NUCLEO-BNRG2A1

- BLE_GattClient_CharacteristicWrite/source/main.cpp
Update the demo to use the new BLEApp class and show how to put ble to sleep by stopping the BLEApp.
> Use new ble app

- BLE_Advertising/CMakeLists.txt
- BLE_Advertising/mbed-os.lib
- BLE_Advertising/source/main.cpp
- BLE_GAP/CMakeLists.txt
- BLE_GAP/mbed-os.lib
- BLE_GattClient_CharacteristicUpdates/CMakeLists.txt
- BLE_GattClient_CharacteristicUpdates/mbed-os.lib
- BLE_GattClient_CharacteristicWrite/CMakeLists.txt
- BLE_GattClient_CharacteristicWrite/mbed-os.lib
- BLE_GattClient_CharacteristicWrite/source/main.cpp
- BLE_GattServer_AddService/CMakeLists.txt
- BLE_GattServer_AddService/mbed-os.lib
- BLE_GattServer_CharacteristicUpdates/CMakeLists.txt
- BLE_GattServer_CharacteristicUpdates/mbed-os.lib
- BLE_GattServer_CharacteristicWrite/CMakeLists.txt
- BLE_GattServer_CharacteristicWrite/mbed-os.lib
- BLE_GattServer_ExperimentalServices/CMakeLists.txt
- BLE_GattServer_ExperimentalServices/mbed-os.lib
- BLE_PeriodicAdvertising/CMakeLists.txt
- BLE_PeriodicAdvertising/mbed-os.lib
- BLE_SecurityAndPrivacy/CMakeLists.txt
- BLE_SecurityAndPrivacy/mbed-os.lib
- BLE_SupportedFeatures/CMakeLists.txt
- BLE_SupportedFeatures/mbed-os.lib
- BLE_SupportedFeatures/mbed_app.json
- BLE_SupportedFeatures/readme.md
- BLE_SupportedFeatures/source/main.cpp
- CONTRIBUTING.md
- README.md
mbed-os-6.10.0 release of mbed-os.
> Update for mbed-os-6.10.0

- README.md
Hi
I added information in order to use baremetal profile with BLE
@pan- 
Thx
> Baremetal information in README

- .github/workflows/run_conditional_ble_feature_compilation.yml
- resources/test_configs/mbed_app_features_00.json
- resources/test_configs/mbed_app_features_01.json
- resources/test_configs/mbed_app_features_02.json
- resources/test_configs/mbed_app_features_03.json
- resources/test_configs/mbed_app_features_04.json
- resources/test_configs/mbed_app_features_05.json
- resources/test_configs/mbed_app_features_06.json
- resources/test_configs/mbed_app_features_07.json
- resources/test_configs/mbed_app_features_08.json
- resources/test_configs/mbed_app_features_09.json
Runs every week but also can be triggered manually or externally (in mbed-os possibly?).
> add workflow for testing conditional compilation

- BLE_PeriodicAdvertising/source/main.cpp
Added event handler to loop modes correctly
> Fix periodic advertising example not looping modes
